name: Automated Tests

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: "30 17 * * *"

jobs:

  ui-tests:
    runs-on: ubuntu-latest
    permissions:
      checks: write
      pull-requests: write
    env:
      SauceDemoBaseUrl: "https://www.saucedemo.com"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Install dependencies
        run: dotnet restore

      - name: Build project
        run: dotnet build

      - name: Install Playwright browsers
        run: pwsh $(find . -type f -name 'playwright.ps1') install --with-deps

      - name: Install Playwright dependencies
        run: npx playwright install-deps

      - name: Run UI tests
        continue-on-error: true
        run: dotnet test --logger "trx;LogFileName=ui-test-results.trx" --results-directory ./TestResults --filter "TestCategory!=API"

      - name: Upload UI test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: ui-test-results
          path: ./TestResults/*.trx

      - name: Publish UI test report
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: UI Test Results
          path: ./TestResults/ui-test-results.trx
          reporter: dotnet-trx
          fail-on-error: false

  api-tests:
    runs-on: ubuntu-latest
    permissions:
      checks: write
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Install dependencies
        run: dotnet restore

      - name: Build project
        run: dotnet build

      - name: Run API tests
        continue-on-error: true
        env:
          DummyJsonBaseUrl: "https://dummyjson.com/"
        run: dotnet test --logger "trx;LogFileName=api-test-results.trx" --results-directory ./TestResults --filter "TestCategory=API"

      - name: Upload API test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: api-test-results
          path: ./TestResults/*.trx

      - name: Publish API test report
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: API Test Results
          path: ./TestResults/api-test-results.trx
          reporter: dotnet-trx
          fail-on-error: false