name: Automated Tests

on:
  push:
    branches: [ main ]
  pull_request:
  schedule:
    - cron: "30 17 * * *"

jobs:

  ui-tests:
    runs-on: ubuntu-latest
    env:
      SauceDemoBaseUrl: "https://www.saucedemo.com"
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Install dependencies
        run: dotnet restore

      - name: Build project
        run: dotnet build

      - name: Install Playwright browsers
        run: pwsh $(find . -type f -name 'playwright.ps1') install --with-deps

      - name: Install Playwright dependencies
        run: npx playwright install-deps

      - name: Run UI tests
        run: dotnet test --logger "trx;LogFileName=ui-test-results.trx" --filter "TestCategory!=API"

  api-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Install dependencies
        run: dotnet restore

      - name: Build project
        run: dotnet build

      - name: Run API tests
        env:
          DummyJsonBaseUrl: "https://dummyjson.com/"
        run: dotnet test --logger "trx;LogFileName=api-test-results.trx" --filter "TestCategory=API"